name = "Toon"
uuid = "616451e9-093a-4ec3-b67a-88f06778d1cb"
version = "1.0.0"
authors = ["Toon Format Contributors"]
description = "Token-Oriented Object Notation (TOON) â€“ A compact, deterministic JSON format for LLM prompts"
license = "MIT"
repository = "https://github.com/abdelrahman-tolba-software-developer/toon_julia"

[compat]
julia = "1.6"
JSON = "0.21, 0.22, 1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

